### PR TITLE
Support for "url of" 

### PR DESCRIPTION
**Pull request by koroandr**
Added support of urls associated with nodes. 
Now if in source there is something like this:
```
url of Class01 is [[http://google.com]]
```
then if you can click this node in PlantUML plugin, the url will be opened in default system browser.

Moreover, relative urls like this:
```
url of Class02 is [[../test.txt]]
```
are treated like file urls, relative to `.puml` diagram file.
For example, if diagram file is `/path/to/diagram.puml` and url is `./resource.jpeg` then the result url will be `/path/to/resource.jpeg`

### CODE REVIEW

**Comment by krasa** [comment]
Cool, I am a little bit concerned about the fact that it is an incubation feature...  http://plantuml.sourceforge.net/incubation.html

Anyways, there are few problems...

* after clicking on the button (Win 7, JDK 1.6.0.45), 
image


* NPE while rendering:
```
@startuml
url of Class01 is [[http://google.com]]
abstract class AbstractList
@enduml
```
```
[ 817661]   WARN - uml.idea.util.ImageWithUrlData -  
java.lang.NullPointerException
	at org.plantuml.idea.util.ImageWithUrlData.createUrl(ImageWithUrlData.java:94)
	at org.plantuml.idea.util.ImageWithUrlData.parseUrls(ImageWithUrlData.java:81)
	at org.plantuml.idea.util.ImageWithUrlData.<init>(ImageWithUrlData.java:32)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.toImagesWithUrlData(PlantUmlToolWindow.java:237)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.renderWithBaseDir(PlantUmlToolWindow.java:172)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.access$500(PlantUmlToolWindow.java:35)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$3$1.run(PlantUmlToolWindow.java:156)
	at org.plantuml.idea.util.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

* the button is rendered differently on the web demo - the plugin puts it only on the top label, but it should be on both:
http://www.plantuml.com/plantuml/svg/SyfFKj2rKt3CoKnELR1IoC_cAYtAKSXFKt02IcGMAqH7PvIK55ZfwvUNb-kbv-UdvwJg9UVdniPoEQ7gBCxF1W00

**Comment by koroandr** [comment]
Fixed problems you mentioned.

As for "incubation" status of the feature - I think, if it won't break anything, it's anyway acceptable. But, of course, it's you to decide.

**Comment by krasa** [comment]
Looks good to me. Thanks!

**Comment by krasa** [comment]
I fixed a performance problem caused by loading of dtd from internets...

**Pull request merged**
