### PR TITLE
Add highlighting for line and block comments.

### PR DESCRIPTION
**Pull request by calmarj**
Fix for: https://github.com/esteinberg/plantuml4idea/issues/97

### CODE REVIEW

**Comment by krasa** [comment]
Block highlight is not working for multiline, is it possible to add?
```
@startuml
' This is a comment on a single line
Bob->Alice : hello
/' You quote alors use slash-and-quote
to split your comments on several
lines '/
@enduml
```

**Comment by calmarj** [comment]
@krasa, I have updated Pattern for block comment and added small for that.

**Comment by krasa** [comment]
Now it highlights everything between 2 block comments
```
@startuml       

/'Alice <-- Bob: another authentication Response'/
Alice <-- Bob: another authentication Response
/'Alice <-- Bob: another authentication Response'/

@enduml

**Comment by krasa** [comment]
btw no need for force push, I can squash it with one button.

**Comment by krasa** [comment]
Non greedy quantifier seems to do the trick

    public final Pattern blockCommentPattern = Pattern.compile("/'(.|\\n)*?'/");

**Comment by krasa** [comment]
Well, either way, it throws java.lang.StackOverflowError in a little bigger file, interesting.

**Comment by krasa** [comment]
I don't think regex can do it, the best I can do is Pattern.compile("/'[^']*'/"), better to parse it manually.

**Comment by calmarj** [comment]
I have tried on PUML file with 4k lines and haven't encountered StackoverflowError for non-greedy quantifier, could you please share the file which creates such error.

**Comment by krasa** [comment]
```
@startuml       bbb
'Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

/'
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
Authentication Response
'/

@enduml
```

I would just do this:
```
private Collection<SourceAnnotation> annotateBlockComments(String source, TextAttributesKey textAttributesKey) {
        Collection<SourceAnnotation> result = new ArrayList<SourceAnnotation>();

        Matcher matcher = startBlockComment.matcher(source);
        Matcher endMatcher = null;
        
        int start = 0;
        while (matcher.find(start)) {
            start = matcher.start();
            
            if (endMatcher == null) {
                endMatcher = endBlockComment.matcher(source);
            }
            if (endMatcher.find(start)) {
                result.add(new SyntaxHighlightAnnotation(matcher.start(), endMatcher.end(), textAttributesKey));
                start = endMatcher.end();
            }
        }
        return result;
    }
```

**Comment by calmarj** [comment]
Agree, updated code with your suggestion and also added test for PlantUmlExternalAnnotator in order to test this functionality.

**Comment by calmarj** [comment]
@krasa , please review one more time

**Comment by krasa** [comment]
Very nice, thanks!

I'll merge it now so I can add other stuff.
There is only one problem, need to ignore whitespaces before a line comment. 
I will change it to "(?<=\n)\\s*('.*)(?=\n)" if you do not have a better idea.

**Pull request merged**
