### PR TITLE
add minimal Gradle based build.

### PR DESCRIPTION
**Pull request by aadrian**
This is a very minimal Gradle based build.
See https://github.com/JetBrains/gradle-intellij-plugin for more details.

Typical usage:
```
%> gradle buildPlugin
%> gradle runIde
```

Possible improvements:
 - specify further or specific IntelliJ versions to test the plug-in with (right now is using latest EAP IC)
 - refactor the project layout to use a Maven layout so that no tweaks are required
 - configure unit testing correctly
 - configure upload/publishing settings too.

### CODE REVIEW

**Comment by aadrian** [comment]
Any news on merging this PR?

**Comment by krasa** [comment]
Nope, I had no time for this plugin yet.

**Comment by aadrian** [comment]
any news?

**Comment by krasa** [comment]
it is for now in https://github.com/esteinberg/plantuml4idea/tree/gradle

**Pull request closed without merging**
